eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

spring:
  zipkin:
    baseUrl: http://zipkin-service:9411
  cloud:
    gateway:
      routes:
        - id: message_route
          uri: http://message-service:8080
          predicates:
            - Path=/message**
