eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: message_route
          uri: http://message-service:8080
          predicates:
            - Path=/message**
        - id: zipkin_route
          uri: http://zipkin-service:9411
          predicates:
            - Path=/oss/zipkin
          filters:
            - RewritePath=/
        - id: eureka_route
          uri: http://eureka-service:8761
          predicates:
            - Path=/oss/eureka
          filters:
            - RewritePath=/
