eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: message_route
          uri: http://message-service:8080
          predicates:
            - Path=/message**
