spring:
  zipkin:
    baseUrl: http://zipkin-service:9411
eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka
logging.level:
  org.springframework.web.servlet.DispatcherServlet: DEBUG
